LIB_NAME = "SJML Paper"

LIB_VERSION_MAJOR = 0
LIB_VERSION_MINOR = 2
LIB_VERSION_PATCH = 0
LIB_VERSION = (LIB_VERSION_MAJOR, LIB_VERSION_MINOR, LIB_VERSION_PATCH)
LIB_VERSION_STR = ".".join([str(n) for n in LIB_VERSION])
